config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: 'pages#home'
  # get "/pages/:page" => "pages#show"
  # root "pages#show", page: "home"

  match '/account' => 'users#account', via: :get

  resources :jamsessions do
    resources :requests, only: [:new, :create, :delete, :index] do
      member do
        put :accept
        put :decline
      end
    end
    resources :posts, only: [:index, :create, :destroy, :new]

  end
  resources :instruments do
    # resources :userinstruments, only: [:index, :create, :edit, :update, :new]
  end
  resources :jam_session_instruments, only: [:new]
  resources :user_instruments, only: [:new]
end

app/models/jam_session.rb
class JamSession < ApplicationRecord
  has_many :requests, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :jam_session_instruments, dependent: :destroy
  has_many :instruments, through: :jam_session_instruments
  belongs_to :user
  has_one_attached :image
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  accepts_nested_attributes_for :jam_session_instruments
  scope :upcoming, -> { where(["ends_at > ?", DateTime.now]) }
end

app/controllers/jamsessions_controller.rb
class JamsessionsController < ApplicationController
  def index
    if params[:location].present?
      @jamsessions = JamSession.upcoming.where("location ILIKE ?", "%#{params[:location]}%")
    else
      @jamsessions = JamSession.upcoming
    end
    if params[:instrument].present? && params[:instrument] != "Search for instrument..."
      @jamsessions = @jamsessions.joins(:instruments).where("instruments.instrument_type ILIKE ?", "%#{params[:instrument]}%")
    end
    if params[:date].present?
      @jamsessions = @jamsessions.where("starts_at > ?", "%#{params[:date]}%")
    end
    @markers = @jamsessions.geocoded.map do |jamsession|
      {
        lat: jamsession.latitude,
        lng: jamsession.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { jamsession: jamsession })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def show
    @jamsession = JamSession.find(params[:id])
    @post = Post.new
    @request = Request.new
    @markers = [
      {
        lat: @jamsession.latitude,
        lng: @jamsession.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { jamsession: @jamsession })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }]
  end

  def new
    @jamsession = JamSession.new
  end

  def create
    @jamsession = JamSession.new(strong_params)
    @jamsession.user_id = current_user.id
    if @jamsession.save
      redirect_to account_path
    else
      render :new
    end
    @jamsession.save
  end

  def edit
    @jamsession = JamSession.find(params[:id])
  end

  def update
    @jamsession = JamSession.find(params[:id])
    @jamsession.update(strong_params)
    # redirect_to users_path
  end

  def destroy
    @jamsession = JamSession.find(params[:id])
    @jamsession.destroy
    # redirect_to users_path
  end

  private

  def strong_params
    params.require(:jam_session).permit(:title, :starts_at, :ends_at, :location, :status, :image, :latitude, :longitude, :description, :max_capacity, :host_id, jam_session_instruments_attributes: [:instrument_id])
  end
end

app/views/jamsessions/_card.html.erb
  <div class="card-jamsession">
    <% if jamsession.image.attached? %>
      <%= cl_image_tag (jamsession.image.key), height: 200, crop: :fill, class: "jamsession-img" %>
    <% else %>
      <%= image_tag 'banner.jpg', height: 200, width: 300, class: "jamsession-img" %>
    <% end %>
    <span class="badge badge-success"><%= jamsession.status %></span>
    <div class="content-card">
      <h4>
      <%= jamsession.location %> | <%= jamsession.starts_at ? jamsession.starts_at.strftime("%A, %b %d") : '' %>
      </h4>
      <h2><%= jamsession.title %></h2>
      <p><%= jamsession.description.slice(0, 150) + "..." %></p>
         <% if current_user.profile_image.attached? %>
          <%= cl_image_tag jamsession.user.profile_image.key, class: 'card-jamsession-user' %>
        <% else %>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "card-jamsession-user" %>
        <% end %>
     </div>
  </div>

app/views/jamsessions/_info_window.html.erb
<h2><%= jamsession.title %></h2>
<p><%= jamsession.description %></p>

app/views/jamsessions/_simple_fields_for_instrument.html.erb
<%= simple_fields_for "jam_session[jam_session_instruments_attributes][]", jamsession.jam_session_instruments.build do |ff| %>
<%= ff.association :instrument, label_method: :instrument_type, label: "Which instrument(s) do you need on your jam session?" %>
<% end %>

app/views/jamsessions/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-4 offset-4">
      <br>
        <br>
          <h3>Create your jam session:</h3>
            <br>
              <%= simple_form_for @jamsession, url: jamsessions_path do |f| %>
              <%= f.input :title, label: "Title:" %>
              <%= f.input :description, label: "Description:" %>
              <%= f.input :location, label: "Location:" %>
              <%= f.input :starts_at, label: "Starts at:" , as: :datetime, html5: true %>
              <%= f.input :ends_at, label: "Ends at:" , as: :datetime, html5: true %>
              <%= f.input :max_capacity, label: "Maximum capacity:" %>
              <%= f.input :image, as: :file, label: "Image:" %>
          <%= f.submit "Submit", class: "btn btn-outline-light" %>
       <% end %>
    </div>
  </div>
</div>

app/views/jamsessions/index.html.erb
<div class="index-container">
  <div class="cards">
    <% @jamsessions.each do |jamsession| %>
    <%= link_to jamsession_path(jamsession) do %>
      <%= render "card", jamsession: jamsession %>
      <% end %>
    <% end %>
  </div>

  <div id="map"
  style="width: 30%; height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

  </div>
</div>

app/views/jamsessions/index_oud.html.erb
<div class="index-container">
  <div class="row">
    <div class="col-6 offset-3">

    <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>

      <div class="card-jamsessions">
        <div class="card-jamsession-infos">
          <% @jamsessions.each do |jamsession| %>
            <%= link_to jamsession_path(jamsession) do %>

            <%= render "card", jamsession: jamsession %>
            <% end %>
          <% end %>
        </div>  
      </div>
    </div>
  </div>
</div>

app/views/jamsessions/new.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-4 offset-4">
      <br>
        <br>
          <h3>Create your jam session:</h3>

              <%= simple_form_for @jamsession, url: jamsessions_path do |f| %>
              <%= f.input :title, label: "Title:" %>
              <%= f.input :description, label: "Description:" %>
              <%= f.input :location, label: "Location:" %>
              <%= f.input :starts_at, label: "Starts at:" , as: :datetime, html5: true %>
              <%= f.input :ends_at, label: "Ends at:" , as: :datetime, html5: true %>
              <%= f.input :max_capacity, collection: 2..20, label: "Maximum capacity:" %>

              <div id="instrument-target">
                <%= render "simple_fields_for_instrument", jamsession: @jamsession %>
              </div>
              <%= link_to "Add a new instrument", new_jam_session_instrument_path, remote: true %>
              <br>
              <br>


              <%= f.input :image, as: :file, label: "Image:" %>
          <%= f.submit "Submit", class: "btn btn-outline-light" %>
       <% end %>
    </div>
  </div>
</div>

app/views/jamsessions/show.html.erb
 <div class="profile-container">
   <div class="row">
     <div class="col-8 offset-2">
           <br>
            <br>
      <div class="card-show-jamsession">
        <% if @jamsession.image.attached? %>
          <%= cl_image_tag (@jamsession.image.key), class: "card-header-image" %>
        <% else %>
          <%= image_tag 'backgo_mfzx8q_2_jfia6a.jpg', class: "card-header-image" %>
        <% end %>
        <div class="card-show-jamsession-infos">
          <h4><%= @jamsession.title %></h4>
            <p><%= @jamsession.description %></p>
      <p><strong><i class="fas fa-music"></i> Looking for musicians that can play: <% @jamsession.instruments.to_a.each do |jamsession| %>
                   <%= jamsession.instrument_type %>
                  <% end %> </strong></p>
                  <p><strong><i class="fas fa-map-marker-alt"></i> <%= @jamsession.location %></strong></p>
                <p><strong><i class="fas fa-calendar-day"></i> <%= @jamsession.starts_at %></strong> </p>
                <p><strong><i class="fas fa-users"></i> <%= @jamsession.status %></strong></p>
            <div class="two-columns">
              <div class="first">
                <p><strong><i class="fas fa-user"></i> Hosted by <%= @jamsession.user.first_name  %><%= @jamsession.user.last_name %></strong></p>
              </div>
              <div class="second">
                <% if current_user.profile_image.attached? %>
                  <%= cl_image_tag @jamsession.user.profile_image.key, class: 'card-jamsession-user' %>
                <% else %>
                  <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "card-jamsession-user" %>
                <% end %>
              </div>
            <div class="button-request">
            <%= simple_form_for [ @jamsession, @request ], url: jamsession_requests_path(@jamsession)  do |f| %>
            <%= f.hidden_field :status, value: "pending" %>
            <%= f.submit "Join this event", class: "btn btn-dark" %>
          <% end %>
        </div>
            </div>
        </div>
      </div>
      <div class="wrap-map-chat">
        <div class="card-other-show-info">
          <div id="map"
            style="width: 100%; height: 700px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
           <div class="container-card-other-show-info">
            <p><b><%= @jamsession.location %></b></p>
            <p><b><%= @jamsession.status %></b></p>
            <p><b><%= @jamsession.starts_at %></b></p>
            <p><b><%= @jamsession.starts_at %></b></p>
          </div>
        </div>
      <div id="posts" data-jamsession-id="<%= @jamsession.id %>">
        <div class="sticky-chat-title">
        <h3>Wanna post a comment on this event?</h3>
        </div>
        <% @jamsession.posts.each do |post| %>
          <div class="post-container" id="post-<%= post.id %>">
            <i class="author">
              <span><%= post.user.full_name %></span>
              <small><%= post.created_at.strftime("%a %b %e at %l:%M%p") %></small>
            </i>
            <p><%= post.content %></p>
            ---------------------------------------------------------
          </div>
        <% end %>
        <%= simple_form_for [ @jamsession, @post ], url: jamsession_posts_path(@jamsession), remote: true do |f| %>
          <%= f.input :content, label: false, placeholder: "Post ##{@jamsession.title}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>