config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: 'pages#home'
  # get "/pages/:page" => "pages#show"
  # root "pages#show", page: "home"

  match '/account' => 'users#account', via: :get

  resources :jamsessions do
    resources :requests, only: [:new, :create, :delete, :index] do
      member do
        put :accept
        put :decline
      end
    end
    resources :posts, only: [:index, :create, :destroy, :new]

  end
  resources :instruments do
    # resources :userinstruments, only: [:index, :create, :edit, :update, :new]
  end
  resources :jam_session_instruments, only: [:new]
  resources :user_instruments, only: [:new]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_instruments, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :instruments, :through => :user_instruments
  has_one_attached :profile_image
  has_many :jam_sessions
  accepts_nested_attributes_for :user_instruments

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
    raise
  end

  # PUT /resource
  def update
    super
    raise
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def account
    @user = current_user 
    @host_user_requests = Request.where(jam_session_id: current_user.jam_sessions)
  end
end

app/views/users/_bio_container.html.erb
<div class="bio-container">
  <% if @user.profile_image.attached? %>
    <%= cl_image_tag @user.profile_image.key,  height: 300, width: 400 %>
  <% else %>
    <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", alt: "avatar-large" %>
  <% end %>
  <div class="bio-text-and-instrument">
    <div class="bio-text">
      <ul class="list-unstyled">
      <h4><b>My info </b></h4>  
      <i class="fas fa-info"></i> 
      <li>
        <%= @user.full_name %>     
      </li>
      <li>
        <%= @user.email %>
      </li>
      <li>
        <%= @user.phone_number %>
      </li>
      </ul>
    </div>
    <div class="bio-instruments">
    <h4><b>Instruments I play</b></h4>
      <ul class="list-unstyled">
      <li>
        <% @user.user_instruments.each do |instrument| %>

          <p>:: <%= Instrument.find(instrument.instrument_id).instrument_type %></p>
          <% instrument.skill_level.times do |num| %>
          <i class="fas fa-star"></i>
          <% end %>
          <% (5 - instrument.skill_level).times do |num| %>
          <i class="far fa-star"></i>
          <% end %>     
          <% end %>
          <br>

          <% if @user == current_user %>
          <br>
          <h6><%= link_to  "Add an instrument", edit_user_registration_path %></h6>  
          <% end %>
          
      </ul>
    </div>
  </div>
</div>

app/views/users/_my_requests.html.erb
<% if request.status == "Accepted" %>
  <div class="card-jamsession">    
      <% if request.jam_session.image.attached? %>
        <%= cl_image_tag (request.jam_session.image.key), height: 200, crop: :fill, class: "jamsession-img" %>
      <% else %>
        <%= image_tag 'banner.jpg', height: 200, width: 300, class: "jamsession-img" %>
      <% end %>
      <span class="badge badge-success"><%= request.jam_session.status %></span>
      <div class="content-card">
        <h4><%= request.jam_session.location %> | <%= request.jam_session.starts_at ? request.jam_session.starts_at.strftime("%A, %b %d") : '' %> </h4>
        <h2><%= request.jam_session.title %></h2>
        <p><%= request.jam_session.description.slice(0, 150) + "..." %></p>
        <% if request.jam_session.user.profile_image.attached? %>
        <%= cl_image_tag request.jam_session.user.profile_image.key, class: 'card-jamsession-user avatar-bordered' %>
        <% else %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "card-jamsession-user avatar-bordered" %>
        <% end %>
      </div>  
  </div>
<% end %>

app/views/users/_requests.html.erb
<div class="card-requests-profile">

    <br>
    <h5><%= request.jam_session.title %></h5>
    <p>Status <%= request.status %></p>
    <h6><%= link_to  request.user.full_name, user_path(request.user) %><span STYLE="font-style: italic"> wants to join your event</span></h6>
    <div class="button-position-profile">
      <div class="one-button-position-profile">
        <%= button_to "Decline", decline_jamsession_request_path(request.jam_session, request), :class => '.button-position-profile-1',  method: :put%> 
      </div>
      <div class="one-button-position-profile">
        <%= button_to "Accept", accept_jamsession_request_path(request.jam_session, request) , method: :put%>
      </div>
    </div>

</div>

app/views/users/account.html.erb
<div class="container">
  <div class="row">
    <div class="col-12"> 
      <%= render "bio_container" %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <h4><b>Upcoming Jam Sessions</b></h4>

      <div class="cards">    
        <% @user.jam_sessions.each do |jamsession| %>
          <%= link_to jamsession_path(jamsession) do %>
            <%= render "jamsessions/card", jamsession: jamsession %>
            
          <% end %>        
        <% end %>

        <% current_user.requests.each do |request| %>
              <%= render "users/my_requests", request: request %>
        <% end %>        
      </div>
    </div>

    <div class="col-6">
      <div class="card-requests">
      <h4><b>Requests for your jam sessions</b></h4>
        <% @host_user_requests.each do |request| %>
        <%= render "users/requests", request: request %>
        
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">


    <div class="col-12"> 

      <%= render "bio_container" %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <h4><b>Upcoming Jam Sessions</b></h4>

      <div class="cards">    
        <% @user.jam_sessions.each do |jamsession| %>
          <%= link_to jamsession_path(jamsession) do %>
            <%= render "jamsessions/card", jamsession: jamsession %>
            
          <% end %>        
        <% end %>

        <% @user.requests.each do |request| %>
            <%= render "users/my_requests", request: request %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>