config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: 'pages#home'
  # get "/pages/:page" => "pages#show"
  # root "pages#show", page: "home"

  match '/account' => 'users#account', via: :get

  resources :jamsessions do
    resources :requests, only: [:new, :create, :delete, :index] do
      member do
        put :accept
        put :decline
      end
    end
    resources :posts, only: [:index, :create, :destroy, :new]

  end
  resources :instruments do
    # resources :userinstruments, only: [:index, :create, :edit, :update, :new]
  end
  resources :jam_session_instruments, only: [:new]
  resources :user_instruments, only: [:new]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
	<footer id="footer">
				<div class="inner">
					<div class="flex flex-3">
						<div class="col">
							<h3>Your account</h3>
							<ul class="alt">
								<li><a href="#">Settings</a></li>
								<li><%= link_to "Log out", destroy_user_session_path %></li>
								<li><a href="#">Help</a></li>
							</ul>
						</div>
						<div class="col">
							<h3>Discover</h3>
							<ul class="alt">
								<li><%= link_to "Jam sessions", jamsessions_path %></li>
								<li><a href="#">Musicians</a></li>
								<li><a href="#">Instruments</a></li>
							</ul>
						</div>
						<div class="col">
							<h3>Music Connects</h3>
							<ul class="alt">
								<li><a href="#">About us</a></li>
								<li><a href="#">Press</a></li>
								<li><a href="#">Contact us</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="copyright">
					<ul class="icons">
						<li><a href="#"><i class="fab fa-twitter"></i></a></li>
						<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="#"><i class="fab fa-instagram"></i></i></a></li>
						<li><a href="#"><i class="fab fa-twitter"></i></a></li>
					</ul>
					&copy; 2020 Music Connects.
				</div>
			</footer>

app/views/shared/_navbar.html.erb
  <nav class="navbar sticky-top">
    <%= link_to root_path do %>
      <h1><i class="fa fa-headphones"></i> Music Connects <span></span></h1>
    <% end %>


  <div class="dropdown-show">
    <div class="search-form">
      <%= form_tag jamsessions_path, method: :get do %>
      <%= text_field_tag :location,
        params[:location],
        class: "form-control",
        placeholder: "Find a Jam Session" %>
      <% end %>
    </div>
    <%= link_to "Create a jam session ", new_jamsession_path, class: "nav-button" %>
    <a class="btn btn-outline-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">&#9776; Menu</a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
        <%= link_to "Account", account_path, class: "dropdown-item" %>
        <%= link_to "Jam sessions", jamsessions_path, class: "dropdown-item" %>
        <%= link_to "Create a jam session", new_jamsession_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", id: "dropdown-item-strong" %>
      </div>
    </div>
  </nav>